[package]
name = "website"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
actix-web.workspace = true
actix-files.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
maud.workspace = true
mime.workspace = true
thiserror.workspace = true
tracing-actix-web.workspace = true
chrono.workspace = true
